# Generated by Django 5.0 on 2023-12-25 04:00

import django.db.models.deletion
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('introduction', models.TextField()),
                ('weather', models.TextField()),
                ('transport', models.TextField()),
                ('banner', models.FileField(upload_to=pages.models.City.get_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('introduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CityGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=pages.models.CityGallery.get_upload_path)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pages.city')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=500, null=True)),
                ('description', models.TextField()),
                ('banner', models.FileField(upload_to=pages.models.Destination.get_upload_path)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pages.category')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pages.city')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=pages.models.DestinationGallery.get_upload_path)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pages.destination')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pages.region'),
        ),
    ]
