# Generated by Django 5.0 on 2023-12-25 04:17
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        UnaccentExtension()
    ]

