# Generated by Django 5.0 on 2024-01-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20231225_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='banner',
            field=models.FileField(default=1, upload_to='regions/'),
            preserve_default=False,
        ),
    ]
