# Generated by Django 5.0 on 2024-01-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_region_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('id',)},
        ),
    ]
